/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconFa6SolidRetweet: typeof import('~icons/fa6-solid/retweet')['default']
    IconFluentMoney16Regular: typeof import('~icons/fluent/money16-regular')['default']
    IconHumbleiconsAtSymbol: typeof import('~icons/humbleicons/at-symbol')['default']
    IconIconamoonComment: typeof import('~icons/iconamoon/comment')['default']
    IconIconamoonShare2Fill: typeof import('~icons/iconamoon/share2-fill')['default']
    IconIonMdStats: typeof import('~icons/ion/md-stats')['default']
    IconMapPin: typeof import('~icons/map/pin')['default']
    IconMaterialSymbolsArrowLeftAlt: typeof import('~icons/material-symbols/arrow-left-alt')['default']
    IconMaterialSymbolsCalendarMonthOutline: typeof import('~icons/material-symbols/calendar-month-outline')['default']
    IconMaterialSymbolsKeyboardArrowDown: typeof import('~icons/material-symbols/keyboard-arrow-down')['default']
    IconMaterialSymbolsNotificationAddOutline: typeof import('~icons/material-symbols/notification-add-outline')['default']
    IconMingcuteBookmarkLine: typeof import('~icons/mingcute/bookmark-line')['default']
    IconMingcuteDocumentLine: typeof import('~icons/mingcute/document-line')['default']
    IconMingcuteFlower2Line: typeof import('~icons/mingcute/flower2-line')['default']
    IconMingcuteGroupLine: typeof import('~icons/mingcute/group-line')['default']
    IconMingcuteHeartLine: typeof import('~icons/mingcute/heart-line')['default']
    IconMingcuteHome5Line: typeof import('~icons/mingcute/home5-line')['default']
    IconMingcuteMailLine: typeof import('~icons/mingcute/mail-line')['default']
    IconMingcuteMore1Line: typeof import('~icons/mingcute/more1-line')['default']
    IconMingcuteMore3Line: typeof import('~icons/mingcute/more3-line')['default']
    IconMingcuteNotificationLine: typeof import('~icons/mingcute/notification-line')['default']
    IconMingcuteSearch2Fill: typeof import('~icons/mingcute/search2-fill')['default']
    IconMingcuteUser2Line: typeof import('~icons/mingcute/user2-line')['default']
    IconMingcuteXrpLine: typeof import('~icons/mingcute/xrp-line')['default']
    IconPhLinkSimple: typeof import('~icons/ph/link-simple')['default']
    IconPhMapPin: typeof import('~icons/ph/map-pin')['default']
    MoreMenu: typeof import('./src/components/MoreMenu.vue')['default']
    PhotoGrid: typeof import('./src/components/PhotoGrid.vue')['default']
    Post: typeof import('./src/components/Post.vue')['default']
    PotentialFollowers: typeof import('./src/components/PotentialFollowers.vue')['default']
    Trending: typeof import('./src/components/Trending.vue')['default']
    WhatsHappening: typeof import('./src/components/WhatsHappening.vue')['default']
    YouMightLike: typeof import('./src/components/YouMightLike.vue')['default']
  }
}
